version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: make site
          command: |
            make site
      - deploy:
          name: push newest site
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "joway.w@gmail.com"
            git config user.name "Joway.CI"
            git commit --allow-empty -m ""
            # Push quietly to prevent showing the token in log
            git push -q https://${DOCS_GITHUB_TOKEN}@github.com/giantswarm/docs.git master
