version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: make site
          command: |
            make site
      - deploy:
          name: push newest site
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "joway.w@gmail.com"
            git config user.name "Joway.CI"
            git add .
            git commit --allow-empty -m `git reflog -1 | sed "s/^.*: //"`
            git push -q https://${GITHUB_TOKEN}@github.com/joway/blog.git master
